-- Migration 035: track conversation name origin for agent auto-naming.
--
-- NULL    = default/placeholder name — an agent-generated title may replace
--           it. Placeholders are (a) the frontend's create-flow name, which
--           stuffs the first user input verbatim into `name` (detected below
--           as a name exactly equal to one of the conversation's own user
--           text messages), and (b) the frontend's default titles.
-- 'agent' = title generated by the agent (ACP session_info_update or claude
--           generate_session_title) — a newer agent title may replace it.
-- 'user'  = explicitly renamed by the user — never overwritten by agents.
--
-- Backfill: only names matching neither placeholder form are marked 'user'
-- (possibly hand-renamed — the DB has no rename history, so stay
-- conservative for them). Everything else stays NULL and remains eligible
-- for agent auto-naming.
ALTER TABLE conversations ADD COLUMN name_source TEXT;
UPDATE conversations SET name_source = 'user'
WHERE name != ''
  AND name NOT IN ('新会话', 'New Conversation')
  AND NOT EXISTS (
    SELECT 1 FROM messages m
    WHERE m.conversation_id = conversations.id
      AND m.type = 'text'
      AND m.position = 'right'
      AND json_extract(m.content, '$.content') = conversations.name
  );
