use std::sync::LazyLock;

use async_trait::async_trait;
use regex::Regex;
use tracing::debug;

use crate::skill_resolver::LoadedAgentSkill;

static THINK_TAG_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<think(?:ing)?>.*?</think(?:ing)?>").expect("valid think-tag regex"));

static LOAD_SKILL_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)\[LOAD_SKILL:\s*([^\]]+)\]").expect("valid load-skill regex"));

/// Remove `<think>...</think>` and `<thinking>...</thinking>` tags from text.
pub fn strip_think_tags(text: &str) -> String {
    THINK_TAG_RE.replace_all(text, "").into_owned()
}

pub fn detect_skill_load_requests(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    for cap in LOAD_SKILL_RE.captures_iter(text) {
        let Some(name) = cap.get(1).map(|m| m.as_str().trim()) else {
            continue;
        };
        if name.is_empty() || names.iter().any(|existing| existing == name) {
            continue;
        }
        names.push(name.to_owned());
    }
    names
}

pub fn has_skill_load_requests(text: &str) -> bool {
    LOAD_SKILL_RE.is_match(text)
}

#[async_trait]
pub trait ISkillLoadService: Send + Sync {
    async fn load_skill_bodies(&self, names: &[String]) -> Vec<LoadedAgentSkill>;
}

/// Result of message middleware processing.
#[derive(Debug, Clone)]
pub struct MiddlewareResult {
    /// The processed message content with private thinking tags stripped.
    pub message: String,
    /// Optional display-only message.
    pub display_message: Option<String>,
    /// System responses generated by middleware side effects.
    pub system_responses: Vec<String>,
}

/// Post-processing pipeline for completed agent messages.
pub struct MessageMiddleware {
    skill_loader: Option<Box<dyn ISkillLoadService>>,
}

impl MessageMiddleware {
    pub fn new() -> Self {
        Self { skill_loader: None }
    }

    pub fn new_with_skill_loader(skill_loader: Option<Box<dyn ISkillLoadService>>) -> Self {
        Self { skill_loader }
    }

    /// Process a completed agent message through the middleware pipeline.
    pub async fn process(&self, message: &str, _user_id: &str, conversation_id: &str) -> MiddlewareResult {
        // TWO different sources, deliberately. Detection reads the RAW message
        // because reasoning models routinely put `[LOAD_SKILL: …]` inside
        // `<think>`; display reads the stripped text because thinking is not for
        // the user. Sharing one `cleaned` value silently dropped every in-think
        // request -- and with no log, so it presented as "the model said it would
        // use a skill, then nothing happened".
        let skill_names = detect_skill_load_requests(message);
        let cleaned = strip_think_tags(message);
        if !skill_names.is_empty() {
            // `info`: this path had NO logging at all, which is exactly why the
            // dropped-request defect could sit unnoticed. Same structured fields
            // as the command channel so the split between the two is measurable.
            let visible_requests = detect_skill_load_requests(&cleaned).len();
            tracing::info!(
                conversation_id = %conversation_id,
                channel = "load_skill_protocol",
                skills = skill_names.len(),
                from_thinking = visible_requests < skill_names.len(),
                "skill load request detected"
            );
        }
        let system_responses = self.load_requested_skills(&skill_names).await;

        MiddlewareResult {
            message: cleaned,
            display_message: None,
            system_responses,
        }
    }

    async fn load_requested_skills(&self, names: &[String]) -> Vec<String> {
        if names.is_empty() {
            return Vec::new();
        }

        let Some(skill_loader) = &self.skill_loader else {
            debug!(
                count = names.len(),
                "Skill load requests detected but no skill loader configured"
            );
            return Vec::new();
        };

        let loaded = skill_loader.load_skill_bodies(names).await;
        if loaded.is_empty() {
            return Vec::new();
        }

        loaded
            .into_iter()
            .map(|skill| {
                // The root is stated up front so the agent resolves the body's own
                // relative references (`references/…`, `scripts/…`) inside the
                // skill instead of against its CWD.
                format!(
                    "[Skill: {}]\nSkill root (resolve every relative path in this body against it): {}\n\n{}",
                    skill.name,
                    skill.source_path.display(),
                    skill.body
                )
            })
            .collect()
    }
}

impl Default for MessageMiddleware {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_think_tags_basic() {
        let input = "Before<think>internal thought</think>After";
        assert_eq!(strip_think_tags(input), "BeforeAfter");
    }

    #[test]
    fn strip_thinking_tags_basic() {
        let input = "<thinking>deep reasoning</thinking>Answer here";
        assert_eq!(strip_think_tags(input), "Answer here");
    }

    #[test]
    fn strip_think_tags_multiline() {
        let input = "Start\n<think>\nline 1\nline 2\n</think>\nEnd";
        assert_eq!(strip_think_tags(input), "Start\n\nEnd");
    }

    #[test]
    fn strip_think_tags_none() {
        let input = "No tags here at all.";
        assert_eq!(strip_think_tags(input), "No tags here at all.");
    }

    #[test]
    fn detect_skill_load_requests_is_case_insensitive_and_dedupes() {
        let requests = detect_skill_load_requests("[load_skill: cron] [LOAD_SKILL: cron] [LOAD_SKILL: pdf]");
        assert_eq!(requests, vec!["cron", "pdf"]);
    }

    struct MockSkillLoader;

    #[async_trait]
    impl ISkillLoadService for MockSkillLoader {
        async fn load_skill_bodies(&self, names: &[String]) -> Vec<LoadedAgentSkill> {
            names
                .iter()
                .map(|name| LoadedAgentSkill {
                    name: name.clone(),
                    body: format!("body for {name}"),
                    source_path: std::path::PathBuf::from(format!("/src/{name}")),
                })
                .collect()
        }
    }

    #[tokio::test]
    async fn middleware_loads_requested_skills() {
        let mw = MessageMiddleware::new_with_skill_loader(Some(Box::new(MockSkillLoader)));
        let result = mw.process("Need [LOAD_SKILL: cron]", "user", "conv").await;

        assert_eq!(result.message, "Need [LOAD_SKILL: cron]");
        // The injected block now also states the skill root -- see
        // `the_injected_body_declares_the_skill_root_absolute_path` for why.
        let injected = &result.system_responses[0];
        assert!(injected.starts_with("[Skill: cron]"));
        assert!(injected.contains("body for cron"));
    }

    /// P1: reasoning models routinely put this meta-decision INSIDE <think>.
    /// Detecting on the STRIPPED text made the request vanish with no log at all,
    /// so the user saw "the model said it would use a skill, then nothing".
    #[tokio::test]
    async fn a_load_request_inside_a_think_block_is_still_honoured() {
        let mw = MessageMiddleware::new_with_skill_loader(Some(Box::new(MockSkillLoader)));
        let result = mw
            .process(
                "<think>I need [LOAD_SKILL: cron] for this</think>Sure, on it.",
                "user",
                "conv",
            )
            .await;

        assert_eq!(
            result.system_responses.len(),
            1,
            "the request must be detected in the RAW text"
        );
        assert!(result.system_responses[0].contains("cron"));
        assert_eq!(
            result.message, "Sure, on it.",
            "the VISIBLE text is still stripped -- detection and display read different sources"
        );
    }

    /// P1 boundary: the same skill inside and outside the block is one request.
    #[tokio::test]
    async fn a_request_repeated_inside_and_outside_the_block_loads_once() {
        let mw = MessageMiddleware::new_with_skill_loader(Some(Box::new(MockSkillLoader)));
        let result = mw
            .process(
                "<think>[LOAD_SKILL: cron]</think>Also [LOAD_SKILL: cron]",
                "user",
                "conv",
            )
            .await;
        assert_eq!(result.system_responses.len(), 1, "dedupe across the think boundary");
    }

    /// P2: without the root, a relative reference in the skill body resolves
    /// against the CWD. The dangerous case is not "file missing" but "the
    /// workspace happens to hold a same-named file", which points the agent at
    /// unrelated user content.
    #[tokio::test]
    async fn the_injected_body_declares_the_skill_root_absolute_path() {
        let mw = MessageMiddleware::new_with_skill_loader(Some(Box::new(MockSkillLoader)));
        let result = mw.process("Need [LOAD_SKILL: cron]", "user", "conv").await;

        let injected = &result.system_responses[0];
        assert!(
            injected.contains("/src/cron"),
            "the skill root must be stated so `references/x.md` resolves inside the \
             skill rather than against the workspace: {injected}"
        );
        assert!(injected.contains("[Skill: cron]"), "the existing header shape is kept");
        assert!(injected.contains("body for cron"));
    }
}
